# -*- coding: utf-8 -*-
"""EugenyMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lRu_VFSJ7M74HaKCsuCxJtDffP3C0BYj
"""

print("Hello World")

a=5
b=2
c=a-b
print(c)

a=4
b=3
c=2
d=(a**2+b**2-c**3)//2
print(d)

a=7.5
h=5
b=3
s=(h*b)/2
print(s)

"""Площадь равнобедренного треугольника равна половине произведения высоты и основания b"""

a=5
b=int(input())
print(a*b)

a=int(input())
b=int(input())
print((a+b)**2)

a=15
b=10
c=int(input())
print((a+b)//c)

a=int(input())
b=int(input())
print(a**2+2*a*b+b**2)

a=int(input())
b=int(input())
c=int(input())
h=int(input())
s=(a*h)/2
p=a+b+c
print(s)
print(p)

a=int(input())
b=int(input())
print(((a**3+14)//5)*b)

a=int(input())
b=int(input())
print(a**2//b)

a=float(input())
b=float(input())
c=int(input())
d=int(input())
s=a//b
g=c*d
h=(s%g)
print(h)

a=int(input())
d=a//86400
h=a//3600%24
m=a//60%60
s=a%60
print(d,h,m,s)

n=int(input())
a=str(n)
b=a+a
c=a+a+a
d=n+int(b)+int(c)
print(d)

